### ISSUE TITLE
Repository named '{}' already exists

### ISSUE THREAD

**Issue by ryaholm** [CSnap/django_git_tinymce#23]
@SLiNv 
Hi Victor, I am having problems fixing a bug and was curious if you had hints towards a solution.

When you go to the "edit repo" section, the repo.forms RepositoryModelForm cleans the 'name' field from the form submission, then checks to see if the repo exists. This is okay if the name of the repo is being changed, however when you are just, for example, changing the description (and want to leave the repo name the same), it still returns "Repo named {} already exists" and blocks the updating of the description. What the form needs is some sort of "old_name" input, which automatically places the old repo name, and if old_name and self.cleaned_data['name'] are the same, it ignores the...
```
query_set = Repository.objects.filter(
			name=name,
			owner=self.request.user
		)
		
		if query_set.exists():
			raise forms.ValidationError(
				"Repository named '{}' already exists".format(name)
			)
```

But I am having a hard time making this logic happen. Any hints on how to fix this bug?

**Comment by SLiNv** [comment]
It is pretty much the same as passing "request" to inside the from. In gituser.views.RepositoryUpdateView.get_form_kwargs, pass the name to the form using kwarg and pop it in form's __init__ before it causes you an unexpected argument error. PR #25 fixes this. I forgot to test this before, thanks for catching this :)

**Comment by ryaholm** [comment]
Thanks for the fix and the explanation!
