### ISSUE TITLE
Fail to Create Due to Post Save Git Operation

### ISSUE THREAD

**Issue by SLiNv** [CSnap/django_git_tinymce#28]
Object creation fails the simple test -- gitusers.tests.py. When tried to create a new repo, a GitError occured.

> GitError at /user1/create/
> Failed to insert entry. Invalid filemode for file - README.md
> Traceback:
> 
> File "/django/core/handlers/exception.py" in inner
>   41.             response = get_response(request)
> 
> File "/django/core/handlers/base.py" in _legacy_get_response
>   249.             response = self._get_response(request)
> 
> File "/django/core/handlers/base.py" in _get_response
>   187.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/django/core/handlers/base.py" in _get_response
>   185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/django/views/generic/base.py" in view
>   68.             return self.dispatch(request, *args, **kwargs)
> 
> File "/django/contrib/auth/mixins.py" in dispatch
>   56.         return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
> 
> File "/django/views/generic/base.py" in dispatch
>   88.         return handler(request, *args, **kwargs)
> 
> File "/django/views/generic/edit.py" in post
>   217.         return super(BaseCreateView, self).post(request, *args, **kwargs)
> 
> File "/django/views/generic/edit.py" in post
>   183.             return self.form_valid(form)
> 
> File "/home/victor/django_git_tinymce/gitusers/views.py" in form_valid
>   77. 		valid_data = super(RepositoryCreateView, self).form_valid(form)
> 
> File "/django/views/generic/edit.py" in form_valid
>   162.         self.object = form.save()
> 
> File "/django/forms/models.py" in save
>   451.             self.instance.save()
> 
> File "/django/db/models/base.py" in save
>   806.                        force_update=force_update, update_fields=update_fields)
> 
> File "/django/db/models/base.py" in save_base
>   846.                 update_fields=update_fields, raw=raw, using=using,
> 
> File "/django/dispatch/dispatcher.py" in send
>   193.             for receiver in self._live_receivers(sender)
> 
> File "/django/dispatch/dispatcher.py" in <listcomp>
>   193.             for receiver in self._live_receivers(sender)
> 
> **File "django_git_tinymce/repos/models.py" in repository_post_save**
>   **75. 		bld.insert(fn, b, os.stat(os.path.join(repo.workdir, fn)).st_mode )**
> 
> Exception Type: GitError at /user1/create/
> Exception Value: Failed to insert entry. Invalid filemode for file - README.md

**Comment by ryaholm** [comment]
Hi Victor,

I just looked into this, made an account and a repo from scratch, etc, and I didn't get an error. Are you trying to make a repo when this occurs?

**Comment by SLiNv** [comment]
No this is not from travis, it happened when I tried to create a new repo at URL /create. I will look into it and see if this is only my end.

**Comment by SLiNv** [comment]
I did some print debugging and researching, found out that it was the difference project environment causing this, the code is actually working good.

On my ubuntu, ```os.stat(os.path.join(repo.workdir, fn)).st_mode``` returns **hex 33204**
The 0100664 file mode means it's a regular file with read/write (user), read/write (group) and read-only (other)

while ```pygit2.GIT_FILEMODE_BLOB``` represents **33188**
0100644 is read-write for the user and read-only for everyone else.
Thus pygit2 complains about Invalid filemode for the newly created file.

 [libgit2 types](https://github.com/libgit2/libgit2/blob/89c332e41b12a72d89de40d63bc568c56a2c336a/tests/resources/typechanges/README.md#types)

**Comment by SLiNv** [comment]
This is due to environment setup, can be closed
